import one from "../../assets/COACHES/1.jpg";
import two from "../../assets/COACHES/2.jpg";
import three from "../../assets/COACHES/3.jpg";
import four from "../../assets/COACHES/4.jpg";
import five from "../../assets/COACHES/5.jpg";
import six from "../../assets/COACHES/6.jpg";
import seven from "../../assets/COACHES/7.jpg";
import eight from "../../assets/COACHES/8.jpg";
import nine from "../../assets/COACHES/9.jpg";
import ten from "../../assets/COACHES/10.jpg";
import eleven from "../../assets/COACHES/11.jpg";
import twelve from "../../assets/COACHES/12.jpg";

export const dataCoaches = [
    {
        id: 1,
        photo: one,
        name: "melissa ray",
        specialization: "Yoga coach",
        moto: "train and enjoy",
        directions: "yoga, meditation, trx, stretching, aero, pilates",
        experience: 5,
        education:"Certified Hatha Yoga teacher training course in San-Fransisco Yoga Academy",
        certificates: "women's practices, meditation with singing bowls, nailing, TRX, stretching, hotstretching, aero stretching, pilates",
        phrase: "Yoga is not about being good at something. It's about being good to yourself.",
        hoursTrained: 483,
        happyClients: 157,
        personalBests: 268,
        searchTerm: ["yoga", "trx", "stretching", "aero", "hotyoga", "hotstretching", "pilates"],
        title: "melissa-ray",
    },

    {
        id: 2,
        photo: two,
        name: "samuel adams",
        specialization: "Fitness coach",
        moto: "let's do it",
        directions: "functional training, healthy back, fitboxing, trx",
        experience: 8,
        education:"higher education in physical education at the Academy of Physical Education in Melbourne.",
        certificates: "functional training, healthy back, fitboxing, trx",
        phrase: "Motivation will get you started, while habit will keep you going.",
        hoursTrained: 856,
        happyClients: 258,
        personalBests: 545,
        searchTerm: ["functional", "healthyback", "fitboxing", "trx"],
        title: "samuel-adams",
    },

    {
        id: 3,
        photo: three,
        name: "sally froning",
        specialization: "Stretching coach",
        moto: "Unlock Your Potential",
        directions: "AERO, TRX, Stretching, Tabata + MFR, Pilates, hot stretching",
        experience: 3,
        education:"higher education in physical education at the Academy of Sport in London.",
        certificates: "stretching, hot-stretching, pilates, aero-stretching, TRX (TRX Training Center)",
        phrase: "Your body will achieve what your mind will believe..",
        hoursTrained: 856,
        happyClients: 258,
        personalBests: 545,
        searchTerm: ["aero", "trx", "stretching", "hotstretching", "mfr", "pilates"],
        title: "sally-froning",
    },

    {
        id: 4,
        photo:four,
        name: "kristy cartis",
        moto: "Building Better Bodies",
        directions: "AERO, TRX, Stretching, Tabata + MFR, Pilates, hot stretching, healthy back",
        experience: 6,
        education:"higher education in physical education at the Academy of Physical Education in Paris.",
        certificates: "stretching, TRX, AERO, MFR, pilates, hot stretching, sport nutrition",
        phrase: "You don't have to be great to start, but you have to start to be great.",
        hoursTrained: 512,
        happyClients: 256,
        personalBests: 335,
        searchTerm: ["aero", "trx", "stretching", "hotstretching", "mfr", "pilates", "healthyback"],
        title: "kristy-cartis",
    },

    {
        id: 5,
        photo: five,
        name: "anna borkovich",
        moto: "Your Health, My Mission",
        directions: "yoga, meditation, trx, stretching, aero, pilates, hot yoga, hot stretching",
        experience: 4,
        education:"Certified Kundalini yoga teacher training course in Sydney Yoga School.",
        certificates: "Kundalini yoga instructor, thai massage diploma, trx, stretching, aero, pilates, hot yoga, hot stretching",
        phrase: "Yoga takes you into the present moment. The only place where life exists.",
        hoursTrained: 312,
        happyClients: 215,
        personalBests: 278,
        searchTerm: ["yoga", "trx", "stretching", "aero", "hotyoga", "hotstretching", "pilates"],
        title: "anna-borkovich",
    },

    {
        id: 6,
        photo: six,
        name: "selena phillips",
        moto: "Discover Your Strength Within",
        directions: "yoga, meditation, stretching, healthy back, hot yoga, hot stretching",
        experience: 3,
        education:"Certified Universal yoga teacher training course in Washington, US.",
        certificates: "yoga, meditation, nailing, stretching, healthy back, hot yoga, hot stretching",
        phrase: "Yoga is the dance of every cell with the music of every breath that creates inner serenity and harmony",
        hoursTrained: 247,
        happyClients: 114,
        personalBests: 289,
        searchTerm: ["yoga", "stretching", "hotyoga", "hotstretching", "healthyback"],
        title: "selena-phillips",
    },

    {
        id: 7,
        photo: seven,
        name: "mary ramos",
        moto: "Push Harder, Achieve Greater",
        directions: "Tabata + MFR, functional training, healthy back, fitboxing, TRX",
        experience: 3,
        education: "higher education in physical education at the Sports Academy in NY.",
        certificates: "Tabata + MFR, functional training, healthy back, fitboxing, TRX",
        phrase: "Every training is a step for success.",
        hoursTrained: 263,
        happyClients: 152,
        personalBests: 286,
        searchTerm: ["mfr", "functional", "healthyback", "fitboxing", "trx"],
        title: "mary-ramos",
    },

    {
        id: 8,
        photo: eight,
        name: "mike kiddom",
        moto: "Sweat Today, Smile Tomorrow",
        directions: "functional training, healthy back, fitboxing, trx",
        experience: 7,
        education:"higher education in physical education at the University of Physical education in Chicago, US.",
        certificates: "functional training, healthy back, fitboxing, trx",
        phrase: "When you feel like quitting, remember why you started.",
        hoursTrained: 652,
        happyClients: 347,
        personalBests: 349,
        searchTerm: ["functional", "healthyback", "fitboxing", "trx"],
        title: "mike-kiddom",
    },

    {
        id: 9,
        photo: nine,
        name: "angela hoppins",
        moto: "Be Your Best Self",
        directions: "yoga, stretching, hot yoga, hot stretching, pilates, aero",
        experience: 6,
        education:"Certified Bikram yoga teacher training course in Branson, US.",
        certificates: "Bikram yoga, meditation, stretching,  hot yoga, hot stretching, pilates, aero",
        phrase: "Do something today that your future self will thank you for.",
        hoursTrained: 547,
        happyClients: 317,
        personalBests: 429,
        searchTerm: ["yoga", "stretching", "hotyoga", "hotstretching", "pilates", "aero"],
        title: "angela-hoppins",
    },

    {
        id: 10,
        photo: ten,
        name: "ksenia larson",
        moto: "Train Smart, Live Fully",
        directions: "Tabata + MFR, functional training, healthy back, fitboxing, TRX, aero",
        experience: 4,
        education: "higher education in physical education at the Fitness Academy in Prague.",
        certificates: "Tabata + MFR, functional training, healthy back, fitboxing, TRX, AERO",
        phrase: "Don't count the days, make the days count.",
        hoursTrained: 289,
        happyClients: 202,
        personalBests: 328,
        searchTerm: ["mfr", "functional", "healthyback", "fitboxing", "trx", "aero"],
        title: "ksenia-larson",
    },

    {
        id: 11,
        photo: eleven,
        name: "tailor swift",
        moto: "Your Goals, My Guidance",
        directions: "functional training, healthy back, fitboxing, trx",
        experience: 8,
        education:"higher education in physical education at the Sports Colleague in Massachusetts, US.",
        certificates: "functional training, healthy back, fitboxing, trx",
        phrase: "Nothing truly great ever came from a comfort zone.",
        hoursTrained: 582,
        happyClients: 361,
        personalBests: 380,
        searchTerm: ["functional", "healthyback", "fitboxing", "trx"],
        title: "tailor-swift",
    },

    {
        id: 12,
        photo: twelve,
        name: "sarah weber",
        moto: "Get Fit, Stay Committed",
        directions: "AERO, TRX, Stretching, Tabata + MFR, Pilates, hot stretching, healthy back",
        experience: 2,
        education:"higher education in physical education at the Fitness and Sport Academy in Miami.",
        certificates: "stretching, TRX, AERO, MFR, pilates, hot stretching",
        phrase: "The best project you'll ever work on is you.",
        hoursTrained: 189,
        happyClients: 111,
        personalBests: 138,
        searchTerm: ["yoga", "stretching", "hotyoga", "hotstretching", "pilates", "aero"],
        title: "sarah-weber",
    }
]